export const ProductMap = {
  '$10 Gift Card': { name: '$10 Gift Card', id: 387 },
  '$125 Gift Card': { name: '$125 Gift Card', id: 375 },
  '$150 Gift Card': { name: '$150 Gift Card', id: 299 },
  '$45 Gift Card': { name: '$45 Gift Card', id: 355 },
  '$80 Gift Card': { name: '$80 Gift Card', id: 319 },
  '$85 Gift Card': { name: '$85 Gift Card', id: 367 },
  '$90 Gift Card': { name: '$90 Gift Card', id: 331 },
  '$93 10lb. Gift Card': { name: '$93 10lb. Gift Card', id: 359 },
  '$95 Gift Card': { name: '$95 Gift Card', id: 363 },
  '1/2 Boneless - B2B': { name: '1/2 Boneless - B2B', id: 143 },
  '10 lb Bone-In - B2B': { name: '10 lb Bone-In - B2B', id: 179 },
  '11 Bone-in': { name: '11 Bone-in', id: 271 },
  '2 Side Special': { name: '2 Side Special', id: 339 },
  '3 Sauce Special': { name: '3 Sauce Special', id: 327 },
  '3 Side Special': { name: '3 Side Special', id: 343 },
  '8 lb Bone-In - B2B': { name: '8 lb Bone-In - B2B', id: 3 },
  '8lb Gift Cards': { name: '8lb Gift Cards', id: 235 },
  '8lb Signature Meal': { name: '8lb Signature Meal', id: 391 },
  '9 lb Bone-In - B2B': { name: '9 lb Bone-In - B2B', id: 175 },
  'Assorted Bagel Tray': { name: 'Bagel Assortment p/p', id: 63 },
  'Blueberry Coffee Cake': { name: 'Blueberry Coffee Cake', id: 311 },
  'Bottled Water': { name: 'Bottled Drinks', id: 51 },
  'Boxed Breakfast': { name: 'Breakfast Box', id: 155 },
  'Signature Breakfast Sandwich Tray': {
    name: 'Breakfast Sandwich p/p',
    id: 27,
  },
  'Broccoli Bacon Bliss Salad': { name: 'Broccoli Bacon Bliss', id: 83 },
  Brownies: { name: 'Brownie', id: 71 },
  'Cookie & Brownie Tray': { name: 'Brownie/Cookie Tray', id: 163 },
  'Cake (Red Velvet/Choc/Coconut/Carrot)': {
    name: 'Cake (Red Velvet/Choc/Coconut/Carrot)',
    id: 371,
  },
  'Assorted Coca-Cola Beverages': { name: 'Canned Drinks', id: 47 },
  'Chicken Salad': { name: 'Chicken Salad', id: 95 },
  'Deep River Kettle Chips': { name: 'Chips', id: 159 },
  'Cobb Salad - Boxed Lunch': { name: 'Cobb Salad - Boxed Lunch', id: 23 },
  'Coffee Carafe': { name: 'Coffee', id: 39 },
  'Coffee Cake Tray': { name: 'Coffee Cake Tray', id: 59 },
  'Assorted Cookies': { name: 'Cookie', id: 67 },
  'Cookie Tin Gift Basket': { name: 'Cookie Tin Gift Basket', id: 303 },
  'Error Discount': { name: 'Error Discount', id: 399 },
  'EZCater/EZOrder Commission': { name: 'EZCater/EZOrder Commission', id: 347 },
  'Final Invoice': { name: 'Final Invoice', id: 147 },
  'Fruit Cup': { name: 'Fruit Cup', id: 279 },
  'Fresh Fruit Tray': { name: 'Fruit Tray', id: 31 },
  'Gallon Lemonade': { name: 'Gallon Lemonade', id: 111 },
  'Gallon Sweet Tea': { name: 'Gallon Tea', id: 115 },
  'Gallon Unsweet Tea': { name: 'Gallon Tea', id: 115 },
  'Garden Salad - Boxed Lunch': { name: 'Garden Salad - Boxed Lunch', id: 195 },
  'Gluten-Free Signature Sandwich Boxed Lunches': {
    name: 'GF Signature Box Lunch',
    id: 379,
  },
  'Gluten-Free Specialty Sandwich Boxed Lunches': {
    name: 'GF Specialty Box Lunch',
    id: 383,
  },
  'Gift Baskets': { name: 'Gift Baskets', id: 251 },
  'Gift Boxes': { name: 'Gift Boxes', id: 199 },
  'Gift Card  - $100': { name: 'Gift Card  - $100', id: 223 },
  'Gift Card  - $25': { name: 'Gift Card  - $25', id: 215 },
  'Gift Card  - $30': { name: 'Gift Card  - $30', id: 231 },
  'Gift Card  - $35': { name: 'Gift Card  - $35', id: 259 },
  'Gift Card  - $60': { name: 'Gift Card  - $60', id: 263 },
  'Gift Card  - $70': { name: 'Gift Card  - $70', id: 267 },
  'Gift Card - $20': { name: 'Gift Card - $20', id: 255 },
  'Gift Card - $40': { name: 'Gift Card - $40', id: 211 },
  'Gift Card - $50': { name: 'Gift Card - $50', id: 183 },
  'Gift Card - $65': { name: 'Gift Card - $65', id: 227 },
  'Gift Card - $75': { name: 'Gift Card - $75', id: 219 },
  'Gluten Free Upgrade': { name: 'Gluten Free Upgrade', id: 127 },
  'Gold Tin': { name: 'Gold Tin', id: 295 },
  'Ham Pound Package - 1 lb.': { name: 'Ham Pound Package - 1 lb.', id: 151 },
  'Ham Salad': { name: 'Ham Salad p/p', id: 91 },
  'Heat and Serve Side Dish': { name: 'Heat and Serve Side Dish', id: 335 },
  'Honey Baked Plate Boxed Lunch': { name: 'Honey Baked Plate', id: 247 },
  'Honey Baked Plate - GF': { name: 'Honey Baked Plate - GF', id: 287 },
  'Honey Baked Plate - Veg': { name: 'Honey Baked Plate - Veg', id: 283 },
  Ice: { name: 'Ice', id: 123 },
  'Ice Pack': { name: 'Ice Pack', id: 203 },
  "King's Hawaiian Rolls": { name: "King's Hawaiian Rolls", id: 243 },
  'Meat & Cheese - Large': { name: 'Meat & Cheese - Large', id: 135 },
  'Meat & Cheese - Med': { name: 'Meat & Cheese - Med', id: 131 },
  'Gallon Orange Juice': { name: 'Orange Juice - Gallon', id: 351 },
  'Orange Juice - Individual': { name: 'Orange Juice - Individual', id: 43 },
  'Breakfast Pastry Tray': { name: 'Pastry Tray p/p', id: 55 },
  'Pecan Pie': { name: 'Pecan Pie', id: 275 },
  'Smashed Potato Salad': { name: 'Potato Salad', id: 87 },
  'Retail Sauce by the Bottle': { name: 'Retail Sauce by the Bottle', id: 323 },
  'Roasted Turkey Breast - B2B': {
    name: 'Roasted Turkey Breast - B2B',
    id: 171,
  },
  'Salad Boxed Lunches': { name: 'TODO - see add ons', id: undefined },
  'Cobb Salad': { name: 'Salad - Cobb Buffet', id: 99 },
  'Garden Salad': { name: 'Salad - Garden Buffet', id: 107 },
  'Veggie Cobb Salad': { name: 'Salad - Veggie Cobb Buffet', id: 103 },
  'The Sandwich Builder Buffet': { name: 'Sandwich Builder Buffet', id: 79 },
  'Sandwich Sliders': { name: 'Sandwich Sliders', id: 307 },
  'Signature Sandwich Boxed Lunches': { name: 'Signature Boxed Lunch', id: 15 },
  'Signature Meat Trays - p/p': { name: 'Signature Meat Trays - p/p', id: 239 },
  'Slider 12-Pack': { name: 'Slider 12-Pack', id: 395 },
  'Smoked Turkey Breast - B2B': { name: 'Smoked Turkey Breast - B2B', id: 167 },
  Soup: { name: 'Soup', id: 191 },
  'Specialty Sandwich Boxed Lunches': { name: 'Specialty Boxed Lunch', id: 19 },
  'Supreme Sandwich Tray': { name: 'Supreme Sandwich Tray', id: 75 },
  'Veggie Cobb Salad - Boxed Lunch': {
    name: 'Veggie Cobb Salad - Boxed Lunch',
    id: 291,
  },
  'Fresh Veggie Tray': { name: 'Veggie Tray', id: 139 },
  'VIP Buffet': { name: 'VIP  Buffet - p/p', id: 7 },
  'Whole Boneless - B2B': { name: 'Whole Boneless - B2B', id: 187 },
  'Whole Frozen Turkey': { name: 'Whole Frozen Turkey', id: 207 },
  'Build-Your-Own Yogurt Parfait': { name: 'Yogurt Parfait', id: 35 },
};

export function mapH4HMenuItemToCrmProductId(
  menuItem: keyof typeof ProductMap,
): number | undefined {
  if (ProductMap[menuItem]) return ProductMap[menuItem].id;
  else return undefined;
}
